# Generated by Django 2.1 on 2018-09-07 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onlineplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_href', models.CharField(blank=True, max_length=255, verbose_name='采集页链接')),
                ('v_pic', models.CharField(max_length=255, verbose_name='封面图')),
                ('v_name', models.CharField(max_length=255, verbose_name='电影名')),
                ('v_text_info', models.TextField(blank=True, default='影片介绍暂时为空', verbose_name='影片介绍')),
                ('v_playurl', models.TextField(blank=True, verbose_name='播放链接')),
                ('v_views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('v_pub_date', models.DateTimeField(default=datetime.datetime(2018, 9, 7, 13, 31, 16, 629056, tzinfo=utc), verbose_name='更新时间')),
            ],
        ),
    ]
