# Generated by Django 2.1 on 2018-09-08 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineplay',
            name='v_belong_to',
            field=models.PositiveIntegerField(default=2, verbose_name='影片类别（网盘/在线）'),
        ),
        migrations.AlterField(
            model_name='onlineplay',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 7, 34, 46, 219555, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
