# Generated by Django 2.1.1 on 2019-02-27 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='宿舍号')),
                ('star', models.IntegerField(verbose_name='内务评级')),
                ('info', models.CharField(max_length=255, verbose_name='简介')),
                ('gender', models.IntegerField(verbose_name='类别（男/女）')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='学号')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('classNum', models.IntegerField(verbose_name='班级')),
                ('gender', models.IntegerField(verbose_name='性别')),
            ],
        ),
        migrations.AddField(
            model_name='dormitory',
            name='stu_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_1', to='manager.Student'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='stu_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_2', to='manager.Student'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='stu_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_3', to='manager.Student'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='stu_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_4', to='manager.Student'),
        ),
    ]
