# Generated by Django 2.1.7 on 2019-03-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bed',
            field=models.IntegerField(default=1, verbose_name='床位'),
        ),
        migrations.AddField(
            model_name='student',
            name='dromitory',
            field=models.IntegerField(default=111, verbose_name='宿舍'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='stu_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_1', to='manager.Student'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='stu_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_2', to='manager.Student'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='stu_3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_3', to='manager.Student'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='stu_4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_4', to='manager.Student'),
        ),
    ]
