# Generated by Django 2.1.1 on 2019-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190308_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='elecFee',
            field=models.IntegerField(blank=True, default=0, verbose_name='电费'),
        ),
        migrations.AddField(
            model_name='student',
            name='waterFee',
            field=models.IntegerField(blank=True, default=0, verbose_name='水费'),
        ),
    ]
