# Generated by Django 2.1.1 on 2019-03-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190310_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='elecFee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='waterFee',
        ),
        migrations.AddField(
            model_name='dormitory',
            name='elecFee',
            field=models.IntegerField(blank=True, default=0, verbose_name='电费'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='waterFee',
            field=models.IntegerField(blank=True, default=0, verbose_name='水费'),
        ),
    ]
