# Generated by Django 2.1.1 on 2019-03-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190310_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='isRepair',
            field=models.IntegerField(default=0, verbose_name='报修'),
        ),
    ]
