# Generated by Django 2.1 on 2018-09-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_code',
            name='code_state',
            field=models.IntegerField(default=0, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_contact',
            field=models.CharField(blank=True, default='无', max_length=256, verbose_name='联系方式'),
        ),
    ]
