# Generated by Django 2.1 on 2018-09-01 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_auto_20180901_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 3, 15, 13, 719479, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
