# Generated by Django 2.1 on 2018-09-08 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_auto_20180907_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='v_belong_to',
            field=models.PositiveIntegerField(default=1, verbose_name='影片类别（网盘/在线）'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 8, 7, 34, 46, 217653, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
