# Generated by Django 2.2.5 on 2020-03-23 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineplay', '0028_auto_20200323_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineplay',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 1, 5, 29, 919306, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
