# Generated by Django 2.2.5 on 2020-03-23 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineplay', '0029_auto_20200323_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineplay',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 10, 31, 55, 384519, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
