# Generated by Django 2.1 on 2018-09-01 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '当前爬虫',
                'verbose_name': '当前爬虫',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='消息URL')),
                ('info', models.TextField(blank=True, null=True, verbose_name='消息内容')),
                ('stat', models.PositiveIntegerField(default=0, verbose_name='消息种类')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='消息时间')),
            ],
            options={
                'verbose_name_plural': '消息表',
                'verbose_name': '消息表',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='spidername', max_length=255, unique=True, verbose_name='爬虫名字')),
                ('menupage_totle', models.PositiveIntegerField(default=0, verbose_name='目录数')),
                ('movie_total', models.PositiveIntegerField(default=0, verbose_name='电影数')),
                ('menupage_success', models.PositiveIntegerField(default=0, verbose_name='已爬取目录数')),
                ('movie_success', models.PositiveIntegerField(default=0, verbose_name='已爬取电影数')),
                ('menupage_fail', models.PositiveIntegerField(default=0, verbose_name='失败目录数')),
                ('movie_fail', models.PositiveIntegerField(default=0, verbose_name='失败电影数')),
                ('status', models.PositiveIntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '总览表',
                'verbose_name': '总览表',
            },
        ),
        migrations.AddField(
            model_name='information',
            name='own',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spidermonitor.Overview', verbose_name='所属爬虫'),
        ),
        migrations.AddField(
            model_name='current',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spidermonitor.Overview', verbose_name='当前爬虫'),
        ),
    ]
