# Generated by Django 2.1 on 2018-09-01 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spidermonitor', '0002_auto_20180901_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current',
            options={},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={},
        ),
        migrations.AlterModelOptions(
            name='overview',
            options={},
        ),
        migrations.AlterField(
            model_name='current',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spidermonitor.Overview', verbose_name='Current spider'),
        ),
        migrations.AlterField(
            model_name='information',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Msg'),
        ),
        migrations.AlterField(
            model_name='information',
            name='own',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spidermonitor.Overview', verbose_name='Belong to'),
        ),
        migrations.AlterField(
            model_name='information',
            name='stat',
            field=models.PositiveIntegerField(default=0, verbose_name='Msg type'),
        ),
        migrations.AlterField(
            model_name='information',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Time'),
        ),
    ]
