# Generated by Django 2.1 on 2018-09-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spidermonitor', '0003_auto_20180901_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overview',
            old_name='menupage_totle',
            new_name='menupage_total',
        ),
    ]
