# Generated by Django 2.2.5 on 2020-05-30 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 12, 39, 4, 340229, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
