# Generated by Django 2.2.5 on 2020-05-30 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200530_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_modefy_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 15, 0, 13, 374353, tzinfo=utc), verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 15, 0, 13, 374321, tzinfo=utc), verbose_name='新建时间'),
        ),
    ]
