# Generated by Django 2.2 on 2020-05-30 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200530_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_modefy_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 27, 26, 336262, tzinfo=utc), verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 16, 27, 26, 336235, tzinfo=utc), verbose_name='新建时间'),
        ),
    ]
