# Generated by Django 2.2 on 2020-06-01 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200602_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_modefy_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 16, 46, 49, 403638, tzinfo=utc), verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 16, 46, 49, 403611, tzinfo=utc), verbose_name='新建时间'),
        ),
    ]
