# Generated by Django 2.1 on 2018-09-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=125, unique=True, verbose_name='用户名')),
                ('user_passwd', models.CharField(max_length=256, verbose_name='密码')),
                ('user_contact', models.CharField(default='无', max_length=256, verbose_name='联系方式')),
                ('user_isvip', models.IntegerField(default=0, verbose_name='是否vip')),
                ('user_creat_time', models.DateTimeField(auto_now_add=True)),
                ('user_vip_type', models.IntegerField(default=0, verbose_name='会员类型')),
            ],
        ),
        migrations.CreateModel(
            name='Vip_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_str', models.CharField(max_length=256, verbose_name='激活码')),
                ('code_type', models.IntegerField(default=0, verbose_name='类型（天数)')),
            ],
        ),
    ]
