# Generated by Django 2.1 on 2018-09-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spidermonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='menupage_fail',
            field=models.PositiveIntegerField(default=0, verbose_name='Menupage failed'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='menupage_success',
            field=models.PositiveIntegerField(default=0, verbose_name='Menu page crawled'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='menupage_totle',
            field=models.PositiveIntegerField(default=0, verbose_name='Menupage num'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='movie_fail',
            field=models.PositiveIntegerField(default=0, verbose_name='Movie failed'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='movie_success',
            field=models.PositiveIntegerField(default=0, verbose_name='Movie crawled'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='movie_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Movie num'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='name',
            field=models.CharField(default='spidername', max_length=255, unique=True, verbose_name='Spider name'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='status',
            field=models.PositiveIntegerField(default=0, verbose_name='Status'),
        ),
    ]
