# Generated by Django 2.1 on 2018-09-01 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_auto_20180901_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 1, 57, 6, 900041, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
