# Generated by Django 2.1.1 on 2018-09-02 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_auto_20180901_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 12, 10, 10, 743204, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
