# Generated by Django 2.1 on 2018-09-07 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_auto_20180902_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 13, 31, 16, 627742, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
