# Generated by Django 2.1 on 2018-09-09 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0033_auto_20180908_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_belong_to',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='影片类别（网盘/在线）'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 9, 5, 13, 48, 159843, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
