# Generated by Django 2.1 on 2018-09-11 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0050_auto_20180911_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 9, 57, 55, 209481, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
