# Generated by Django 2.1 on 2018-09-11 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0051_auto_20180911_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 10, 33, 25, 188281, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
