# Generated by Django 2.1.7 on 2019-03-27 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0053_auto_20180911_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='v_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 8, 12, 17, 906057, tzinfo=utc), verbose_name='最后更新时间'),
        ),
    ]
