# Generated by Django 2.2.5 on 2020-03-22 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 12, 46, 16, 376183, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
