# Generated by Django 2.2 on 2020-05-29 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Babaili_jiaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField(verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='作者')),
                ('contact_method', models.CharField(blank=True, max_length=255, verbose_name='联系方式')),
                ('other_info', models.TextField(blank=True, verbose_name='备注信息')),
                ('babaili_jiaji_type', models.CharField(blank=True, max_length=255, verbose_name='类型')),
                ('origin_full_url', models.CharField(blank=True, max_length=255, verbose_name='来源')),
                ('is_solved', models.BooleanField(blank=True, default=False, verbose_name='是否已处理')),
                ('report_date', models.DateTimeField(default=datetime.datetime(2020, 5, 29, 1, 3, 46, 777008, tzinfo=utc), verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='书名')),
                ('book_pic', models.CharField(max_length=255, verbose_name='封面图')),
                ('book_author', models.CharField(max_length=255, verbose_name='作者')),
                ('book_category', models.CharField(default='未分类', max_length=255, verbose_name='图书类别')),
                ('book_infos', models.TextField(verbose_name='图书信息（出版社等）')),
                ('book_description', models.TextField(verbose_name='内容简介')),
                ('book_origin', models.TextField(verbose_name='采集页')),
                ('book_pan_1', models.TextField(blank=True, verbose_name='网盘链接 1')),
                ('book_pan_2', models.TextField(blank=True, verbose_name='网盘链接 2')),
                ('book_pan_3', models.TextField(blank=True, verbose_name='网盘链接 3')),
                ('book_pan_pass', models.CharField(blank=True, max_length=255, verbose_name='网盘密码(1+2+3)')),
                ('book_rating', models.CharField(max_length=255, verbose_name='(豆瓣）评分')),
                ('book_valid', models.IntegerField(default=1, verbose_name='网盘链接是否可用')),
                ('book_views', models.PositiveIntegerField(default=0, verbose_name='阅读次数')),
                ('book_pub_date', models.DateTimeField(default=datetime.datetime(2020, 5, 29, 1, 3, 46, 776325, tzinfo=utc), verbose_name='更新时间')),
            ],
        ),
    ]
