# Generated by Django 2.2.5 on 2020-05-30 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_babaili_jiaji_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babaili_jiaji',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 12, 38, 25, 900489, tzinfo=utc), verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 12, 38, 25, 899799, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
