# Generated by Django 2.2.5 on 2020-03-22 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200322_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_pan_pass',
            field=models.CharField(blank=True, max_length=255, verbose_name='网盘密码(1+2+3)'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 22, 57, 171931, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
