# Generated by Django 2.2.5 on 2020-03-23 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200323_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_catogory',
            new_name='book_category',
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 1, 5, 29, 916712, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
