# Generated by Django 2.2.5 on 2020-05-24 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200524_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noty_title', models.CharField(max_length=255, verbose_name='标题')),
                ('noty_author', models.CharField(max_length=255, verbose_name='发布人')),
                ('noty_content', models.TextField(verbose_name='内容')),
                ('noty_date', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 14, 34, 52, 669082), verbose_name='发布时间')),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 14, 34, 52, 668454), verbose_name='更新时间'),
        ),
    ]
