# Generated by Django 2.2.5 on 2020-05-24 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_notify',
            name='noty_date',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 14, 35, 58, 634203), verbose_name='更新时间'),
        ),
    ]
