# Generated by Django 2.2.5 on 2020-05-24 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200524_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_notify',
            name='noty_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 6, 42, 19, 27488, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 6, 42, 19, 26856, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
