# Generated by Django 2.2.5 on 2020-05-29 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200524_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Babaili_jiaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField(verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='作者')),
                ('contact_method', models.CharField(blank=True, max_length=255, verbose_name='联系方式')),
                ('other_info', models.TextField(blank=True, verbose_name='备注信息')),
                ('babaili_jiaji_type', models.CharField(blank=True, max_length=255, verbose_name='类型')),
                ('origin_full_url', models.CharField(blank=True, max_length=255, verbose_name='来源')),
                ('is_solved', models.BooleanField(blank=True, verbose_name='是否已处理')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 29, 0, 15, 53, 285554, tzinfo=utc), verbose_name='时间')),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 0, 15, 53, 284842, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
