# Generated by Django 2.2.5 on 2020-05-29 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20200529_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babaili_jiaji',
            name='date',
        ),
        migrations.AddField(
            model_name='babaili_jiaji',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 0, 27, 25, 32406, tzinfo=utc), verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='babaili_jiaji',
            name='is_solved',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否已处理'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 0, 27, 25, 31685, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
